### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by Yuri05** [msevestre/DCI#1]
clean up header comments

**Comment by Yuri05** [comment]
Hmm, seems it's already done. So why do I still get old DCI headers along with SimModel?

**Comment by msevestre** [comment]
you have to update the submodule. This is not done automatically

git submodule update --init --recursive

**Comment by Yuri05** [comment]
Did it. Still getting old DCI headers...

**Comment by rwmcintosh** [comment]
I think you need something like this:
```
git submodule update --recursive
```

Do that from the main repository directory, not the submodule directory

**Comment by Yuri05** [comment]
Tried it - still old DCI

**Comment by msevestre** [comment]
Where are you getting old headers? In which project?

**Comment by Yuri05** [comment]
SimModel\src\DCI\includes\DCI

**Comment by msevestre** [comment]
Are you sure this is using a submodule here?

**Comment by rwmcintosh** [comment]
Yes, that's a submodule. When I click through to the source on github, it shows the old comments as well. Maybe submodules are tied to a specific revision?

Investigating that.

**Comment by msevestre** [comment]
The update command would be useless otherwise

**Comment by rwmcintosh** [comment]
looks like what's required is cd into the submodule, then pull, then cd to main repo, then commit.

That updates the revision being used to link the git submodule.

Juri, you might be able to use just git pull to get that change for DCI

**Comment by Yuri05** [comment]
OK, performing pull **on the sub-module** (src/DCI) did the trick.
Do you see any possibility to include this into the "parent" pull of the repository? Otherwise you need exactly to know all the sub modules and pull them separately every-time

**Comment by msevestre** [comment]
.i have used the exact same syntax to update scripts, no problem.

We need to investigate in more details

**Comment by rwmcintosh** [comment]
I had already updated on simmodel and pushed that, so maybe you'll have to deal with that when you commit.

You can definitely loop on submodules and pull them all at once. 

```
git submodule foreach --recursive git pull origin 
```

**Comment by msevestre** [comment]
What version of git are you using?

**Comment by rwmcintosh** [comment]
PS D:\Repos\Open Pharma\SPSuite.SimModel> git --version
git version 2.11.1.windows.1

**Comment by Yuri05** [comment]
2.11.0.3
